name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: cat hola.php

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world segundo"