name: Deploy to server

on: push

jobs:
  first_job:
    name: Tutorial codigoFacilito action
    runs-on: ubuntu-latest

    env:
      NAME: codigoFacilito

    steps:
      - name: Working dir
        run: echo $GITHUB_OUTPUT

  second_job:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world segundo ${{ github.ref }}"