name: Deploy to server

on: push

jobs:
  first_job:
    name: Tutorial codigoFacilito action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "codigoFacilito", "bootcamp github actions"]

    steps:
      - name: Print mensaje
        run: echo "${{ matrix.message }}"