name: Deploy to server

on: push

jobs:
  first_job:
    name: Tutorial codigoFacilito action
    runs-on: ubuntu-latest

    env:
      NAME: codigoFacilito

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name:
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test-log